DELETE http://localhost:3000/api/project/6376086a9df889cada3a52e5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmY5MmRiZWE2Mzg5YmY4OThmOWYxYiIsImlhdCI6MTY2ODI3NDI0MCwiZXhwIjoxNjY4MzYwNjQwfQ.ozvSCOmJobfFZNTrOcErfTUWNZxQZqncNcyJciIK2ZY

{
    "description": "note two description",
    "category": "category2",
    "background": "background2",
    "access": "private",
    "isFavorite": false,
}