version: "3.8"

services:
  app:
    build:
      target: production
    entrypoint:
      - /bin/sh
    ports:
      - 3000:${APP_PORT}
    environment:
      MONGO_URL: ${ATLAS_URL}
      NODE_ENV: production
    command:
      - -c
      - yarn start:prod
