version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker/mongo/data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

  metasave:
    container_name: metasave
    # image: metasave
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: yarn start
    networks:
      - mongo-network
    depends_on:
      - mongo
    restart: unless-stopped

  # ngrok:
  #   container_name: ngrok
  #   image: ngrok/ngrok
  #   ports:
  #     - 4040:4040
  #   volumes:
  #     - ./docker/ngrok/data:/home/ngrok/.ngrok2/
  #   command: ["http", "--region=us", "metasave:3000"]
  #   networks:
  #     - ngrok-network
  #   depends_on:
  #     - metasave
  #   restart: unless-stopped

networks:
  mongo-network:
  ngrok-network:
