version: "3.7"

services:
  server:
    container_name: metasave-server
    # image: metasave-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:${APP_PORT}
    volumes:
      - ./:/app
    command: yarn start
    networks:
      - mongo-network
    depends_on:
      - mongo
      - ngrok
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - 27017:27017
    volumes:
      - ./docker/mongo/data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    ports:
      - 4040:4040
    volumes:
      - ./docker/ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    command: ["ngrok", "http", "8080"]
    networks:
      - ngrok-network
    restart: unless-stopped

networks:
  mongo-network:
  ngrok-network:
