version: "3.7"

services:
  server:
    container_name: metasave-server
    image: metasave-server
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
    networks:
      - mongo-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo/data:/data/db
    networks:
      - mongo-network
    restart: unless-stopped

networks:
  mongo-network:
