version: "3.8"

services:
  app:
    container_name: metasave-api
    image: ghcr.io/thuongtruong1009/metasave:main
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - 3000:${APP_PORT}
    volumes:
      - .:/app
    networks:
      - common
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo/${DB_NAME}
    command: yarn dev

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - 27017:27017
    networks:
      - common
    restart: unless-stopped

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:alpine
    ports:
      - 4040:4040
    volumes:
      - ./docker/ngrok/data:/home/ngrok/.ngrok2/
    command: http host.docker.internal:${APP_PORT}
    networks:
      - common
    depends_on:
      - app
    restart: unless-stopped

networks:
  common:
